name: docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      # - name: Get pip cache dir
      #   id: pip-cache
      #   run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Install requirements
        run: |
          pip3 install sphinx-rtd-theme

      - name: Install dependencies
        run: |
          pip3 install scikit-learn
          pip3 install git+https://github.com/reimerlab/tamarind.git
          pip3 install git+https://github.com/reimerlab/dotmotif/
          python3 -m pip install datajoint
          python3 -m pip install  -r ./requirements.txt
      - name: Install caveclient dependencies
        run: |
          python3 -m pip install \
          cloud-volume==8.27.0 \
          caveclient==5.11.0 \
          python-dotenv

      - name: Add any new modules
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          REPO_NAME=$(basename -s .git $REPO_URL)
          REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          echo $REPO_NAME
          rm docs/$REPO_NAME.rst
          sphinx-apidoc -o docs $REPO_NAME/
      - name: Build docs
        run: |
          cd docs
          make html

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
